name: LinkedIn Job Scraper

on:
  # Run on schedule (every hour)
  schedule:
    - cron: '0 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main branch (for testing)
  push:
    branches: [ main ]

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright browsers
      run: |
        echo "Installing Playwright browsers..."
        playwright install chromium
        playwright install-deps
        echo "Verifying browser installation..."
        ls -la ~/.cache/ms-playwright/ || echo "Playwright cache directory not found"
        
    - name: Debug environment
      run: |
        echo "Python version: $(python --version)"
        echo "Playwright version: $(pip show playwright | grep Version)"
        echo "Current directory: $(pwd)"
        echo "Environment variables:"
        env | grep -E "(PLAYWRIGHT|DISPLAY)" || echo "No Playwright/Display env vars"
        
    - name: Run LinkedIn job scraper
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        LINKEDIN_STATE_JSON: ${{ secrets.LINKEDIN_STATE_JSON }}
      run: |
        python main.py
        
    - name: Clean up sensitive files
      if: always()
      run: |
        rm -f linkedin_state.json
        
    - name: Upload debug artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-artifacts
        path: |
          *.png
          *.log
        retention-days: 7
